name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 0 * * *'   
    - cron: '0 6 * * *'   
    - cron: '0 12 * * *'  
    - cron: '0 18 * * *' 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://calculadora-creditos-uva.streamlit.app/
